import Navbar from "@/ui/navbar/navbar";
import "@/ui/globals.css";
import "@/ui/headings.css";
import styles from "./page.module.css";
import { blackHanSans, balsamiqSans } from "@/ui/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Basket Places</title>
      </head>
      <body
        className={`${balsamiqSans.className} antialiased ${blackHanSans.variable}`}
      >
        <main className={styles.main}>{children}</main>

        <Navbar />
      </body>
    </html>
  );
}
