import Navbar from "@/ui/navbar/navbar";
import "../ui/globals.css";
import { mulish } from "@/ui/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Basket Places</title>
      </head>
      <body className={`${mulish.className} antialiased`}>
        <main>{children}</main>

        <Navbar />
      </body>
    </html>
  );
}
